name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd mobile_app
          flutter pub get

      - name: Build release APK
        run: |
          cd mobile_app
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: musicy-app-release
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
